USE [master]
GO

/****** Object:  Database [TaskTrackerDB]    Script Date: 29.12.2023. 14:58:56 ******/
CREATE DATABASE [TaskTrackerDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaskTrackerDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TaskTrackerDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TaskTrackerDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TaskTrackerDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaskTrackerDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TaskTrackerDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TaskTrackerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TaskTrackerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TaskTrackerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TaskTrackerDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TaskTrackerDB] SET  MULTI_USER 
GO

ALTER DATABASE [TaskTrackerDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TaskTrackerDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TaskTrackerDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TaskTrackerDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TaskTrackerDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TaskTrackerDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TaskTrackerDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TaskTrackerDB] SET  READ_WRITE 
GO


